Repository saulpw/visidata, pull requests merged in 2024-09, with the labels that each got.

#2527 Add a new ColumnsGuide
  visidata/guide.py
  visidata/guides/ColumnsGuide.md
Labels: waiting on maintainer

#2528 [docs] add note that regex operations apply to display values #2481
  visidata/ddw/regex.ddw
  visidata/man/vd.inc
Labels: documentation, waiting on maintainer

#2529 Add the SlideGuide describing column and row movement
  visidata/guides/SlideGuide.md
Labels: waiting on maintainer

#2530 Add a new ClipboardGuide describing cut/copy/paste
  visidata/guides/ClipboardGuide.md
Labels: waiting on maintainer

#2443 [grep-] add loader for output of grep/ripgrep
  dev/formats.jsonl
  docs/formats.md
  sample_data/smiths-json.grep
  sample_data/smiths-standard.grep
  tests/golden/load-grep-json.grep
  tests/golden/load-grep-standard.grep
  tests/load-grep-json.vd
  tests/load-grep-standard.vd
  visidata/guide.py
  visidata/guides/GrepSheet.md
  visidata/loaders/grep.py
Labels: 3.1, waiting on maintainer

#2532 Add a new guide about the MemorySheet
  visidata/guides/MemorySheet.md
Labels: waiting on maintainer

#2503 [input-] keep inputMultiple() input during redo
  visidata/_input.py
Labels: waiting on maintainer

#2533 Add a SplitPaneGuide
  visidata/guides/SplitpaneGuide.md
Labels: waiting on maintainer

#2537 [guide] Add a basic ModifyGuide
  visidata/guides/ModifyGuide.md
Labels: waiting on maintainer
