Repository saulpw/visidata, pull requests merged in 2025-01, with the labels that each got.

#2558 Add a guide for the AggregatorSheet
  visidata/guides/AggregatorsSheet.md
Labels: waiting on maintainer

#2665 [canvas- graph-] fix handling of label chars with screen width > 1
  visidata/canvas.py
  visidata/graph.py
Labels: waiting on maintainer

#2664 [disp] Rename disp_pixel_random to disp_graph_pixel_random
  docs/graphics.md
  visidata/canvas.py
  visidata/deprecated.py
  visidata/man/vd.1
  visidata/man/vd.txt
  visidata/man/visidata.1
Labels: waiting on contributor

#2669 [expr-] add command addcol-iter to make a col from iterator
  tests/addcol-iter.vdj
  tests/golden/addcol-iter.tsv
  visidata/expr.py
  visidata/tests/test_commands.py
Labels: waiting on maintainer

#2673 [columns-] describe key-selected action as set, not toggle
  visidata/metasheets.py
Labels: confirm-fix

#2656 [features-] sysedit: modify cell only if editor changes value
  visidata/_input.py
  visidata/features/sysedit.py
Labels: confirm-fix

#2668 [form-] fix underlining of substrings by FormCanvas
  visidata/form.py
Labels: confirm-fix

#2663 [input-] fix word locator for Ctrl+Right motion
  visidata/_input.py
Labels: confirm-fix

#2680 [fixed-] use empty str for null_value in fixed width sheet
  visidata/loaders/fixed_width.py
Labels: confirm-fix

#2671 [errors-] create Error(s)Sheet only if it is not already open
  visidata/textsheet.py
Labels: waiting on contributor
